import type { NextPage } from 'next'
import Head from 'next/head'
import ButtonRokket from '../components/ButtonRokket'
import { gql, useMutation } from "@apollo/client";
import client from "../apollo-client";
import { useEffect } from 'react';

const SIGN_UP = gql`
  mutation($input: SignUpInput!) {
    signUp( input: $input){
      id
      name
      email
    }
  }
`

const Home: NextPage = () => {
  const [ makeSignUp, result ] = useMutation(SIGN_UP)

  const handleClick = () => {
    makeSignUp({
      variables: {
        input: {
          name: "rok",
          email:"rokket@gmail.com",
          password:"12345"
        }
      }
    })
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world!</h1>
      <ButtonRokket  onClick={handleClick}>Button</ButtonRokket>
    </div>
  )
}

export default Home
